sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
  - '6'
  - '4'
before_script:
  - npm prune
script:
  - npm run test
  - npm run find-new-rules
  - npm run find-new-rules-es6
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  only:
    - master
