sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '5'
  - '6'
  - '0.12'
  - '0.10'
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
  # detect if the current build's node version is < 4
  # if yes, install latest eslint version 2.x
  # if not, install latest eslint version 3.x
  - if [[ `node -v | sed 's/[^0-9\.]//g'` < 4 ]]; then npm i eslint@^2.0.0; else npm i eslint@^3.0.0; fi
  # install latest eslint-config-idiomatic
  - npm i eslint-config-idiomatic@latest
script:
  - npm run test
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  only:
    - master
